### ISSUE TITLE
bot每收到一条消息就会产生一句Registering internal users....

### ISSUE THREAD

**Issue by SnowMoonSS** [Karlatemp/LuckPerms-Mirai#112]
![image](https://user-images.githubusercontent.com/21017431/156752824-30ac30ba-6ff4-419a-abca-8f9c27ef8b42.png)
不管这个人曾经有没有发送过消息，bot都会产生这条日志
mirai版本：2.10.0
luckperms版本：2.10.0-dev-5+null

**Comment by Karlatemp** [comment]
Try 2.10.0-dev-6+null

**Comment by SnowMoonSS** [comment]
`Registering internal users....`没有了，但是使用mcl进行更行的时候：
```
snowmoonss@ubuntu-vm-server:~/mcl$ ./mcl -z
  14:23:24 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  14:23:24 [INFO] https://github.com/iTXTech/mirai-console-loader
  14:23:24 [INFO] This program is licensed under GNU AGPL v3
  14:23:24 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
  14:23:25 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.0
  14:23:25 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.0
  14:23:26 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  14:23:26 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  14:23:26 [INFO] Verifying "io.github.karlatemp:luckperms" v
  14:23:26 [ERROR] "io.github.karlatemp:luckperms" is corrupted.
  14:23:26 [ERROR] Failed to verify package "io.github.karlatemp:luckperms"
  14:23:26 [ERROR] com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 16 column 6 path $.repo.
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseLoad(ScriptManager.java:98)
        at org.itxtech.mcl.Loader.lambda$start$2(Loader.java:172)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:172)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 16 column 6 path $.repo.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 28 more

  14:23:26 [INFO] Fetching Mirai Console Loader Announcement...
  14:23:26 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
```

**Comment by SnowMoonSS** [comment]
今天又试了下，能正常更新了
