### ISSUE TITLE
相关报错？

### ISSUE THREAD

**Issue by Nov-Mio** [Karlatemp/LuckPerms-Mirai#139]
不知道怎么解决惹

- 15:18:51 [INFO] Verifying "io.github.karlatemp:luckperms" v2.10.0-dev-6+null
  15:18:51 **[ERROR] "io.github.karlatemp:luckperms" is corrupted.**
  15:18:51 [INFO] Updating "io.github.karlatemp:luckperms" to v2.10.0-dev-6+null
  15:18:51 **[ERROR] java.io.IOException: Server returned HTTP response code: 429 for URL:** https://karlatemp.coding.net/p/pub/d/pub/git/raw/master/lpm/LuckPerms-Mirai-2.10.0-dev-6%2Bnull-all.jar
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.itxtech.mcl.impl.DefaultDownloader.download(DefaultDownloader.java:49)
        at org.itxtech.mcl.module.builtin.MDownloader$MultithreadingDownloaderImpl.download(MDownloader.java:86)
        at org.itxtech.mcl.module.builtin.Updater.down(Updater.java:221)
        at org.itxtech.mcl.module.builtin.Updater.downloadFile(Updater.java:185)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:151)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:117)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:188)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:188)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
**Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL:** https://karlatemp.coding.net/p/pub/d/pub/git/raw/master/lpm/LuckPerms-Mirai-2.10.0-dev-6%2Bnull-all.jar
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3114)
        at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
        at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
        at java.base/java.net.URLConnection.getContentLength(URLConnection.java:492)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:394)
        at org.itxtech.mcl.impl.DefaultDownloader.download(DefaultDownloader.java:48)
        ... 10 more

 Downloading luckperms-2.10.0-dev-6+null.jar [==============================]

 Downloading luckperms-2.10.0-dev-6+null.jar.sha1 [==============================] 84 B
  15:18:52 **[ERROR] The local file "io.github.karlatemp:luckperms" is still corrupted, please check the network.**
  15:18:52 [INFO] Verifying "com.hcyacg:pixiv" v1.7.4
  15:18:52 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  15:18:52 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.12.1
2022-10-08 15:18:53 I/main: Starting mirai-console...
2022-10-08 15:18:53 I/main: Backend: version 2.12.1, built on 2022-07-31 17:49:27.
2022-10-08 15:18:53 I/main: Frontend Terminal: version 2.12.1, provided by Mamoe Technologies
2022-10-08 15:18:53 I/main: Welcome to visit https://mirai.mamoe.net/
2022-10-08 15:18:53 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-10-08 15:18:53 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-10-08 15:18:53 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-10-08 15:18:53 **E/main: Failed to init MiraiConsole.
java.util.zip.ZipException: zip END header not found**
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1597)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1488)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1495)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1299)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1262)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:842)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init0(JvmPluginClassLoader.kt:225)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt:221)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN$Companion.newLoader(JvmPluginClassLoader.kt:325)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:182)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:66)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:192)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:138)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:148)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:178)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:194)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:194)
        at org.itxtech.mcl.Loader.main(Loader.java:84)

**Comment by Karlatemp** [comment]
编辑 config.json 删除lp的记录

然后手动下载安装

**Comment by Nov-Mio** [comment]
已经解决，十分感谢
