### ISSUE TITLE
在最新版本出现下载报错

### ISSUE THREAD

**Issue by BlueFunny19** [Karlatemp/LuckPerms-Mirai#144]
在 Update 过程中报错
```
10:44:26 [ERROR] "io.github.karlatemp:luckperms" is corrupted.
10:44:26 [INFO] Updating "io.github.karlatemp:luckperms" to v2.10.0-dev-6+null
Downloading luckperms-2.10.0-dev-6+null.jar [==============================] 84 B                    
Downloading luckperms-2.10.0-dev-6+null.jar.sha1 [==============================] 84 B                    
10:44:26 [ERROR] The local file "io.github.karlatemp:luckperms" is still corrupted, please check the network.
```
在启动过程中报错
```
2022-12-12 10:44:27 E/main: Failed to init MiraiConsole.
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init0(JvmPluginClassLoader.kt:271)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init1(JvmPluginClassLoader.kt:263)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt:258)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN$Companion.newLoader(JvmPluginClassLoader.kt:371)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:209)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:67)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:189)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:135)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:145)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:279)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
	Suppressed: java.lang.RuntimeException: Failed to initialize new JvmPluginClassLoader, file=/home/debian/Bots/ChatGPT/bot/plugins/luckperms-2.10.0-dev-6+null.jar
		at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init1(JvmPluginClassLoader.kt:265)
		... 27 more
```
使用的版本是 Mirai Console 2.13.2
纯CLI版本，非GUI版本

**Comment by cssxsh** [comment]
https://github.com/Karlatemp/LuckPerms-Mirai/issues/142

这个的原因
